config/routes.rb
Rails.application.routes.draw do

  root :to => 'categories#index'

  resources :categories do 
    resources :transactions
    resources :incomes
  end
  
  resources :transactions
  resources :incomes
  

end

app/models/income.rb
class Income < ActiveRecord::Base
    # income should have a name and amount in order to be added to the db
    validates :name, presence: true
    validates :amount, presence: true
    belongs_to :category
    # before_save :check_account
    


    # def check_account
    
    #     if Income.exists?(:id => 1)
    #         balance = Income.first.amount + self.amount
    #         Income.first.update(:amount => balance)
    #         false
    #     else
    #         true
    #     end

    # end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = Income.all
    if params.has_key?(:category_id)
      @category = Category.find(params[:category_id])
      @incomes = Category.find(params[:category_id]).incomes
    end
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    # byebug
    @income = Income.new
    if params.has_key?(:category_id)
      @category = Category.find(params[:category_id])
      @income = @category.incomes.new
    else
      @categories = Category.all
    end
  end

  # GET /incomes/1/edit
  def edit
    @categories = Category.all
  end

  # POST /incomes
  # POST /incomes.json
  def create
    # @income = Income.new(income_params)
    category_id = (params[:category_id] or params[:income][:category_id])
    # Retrieve the id of the category that's passed in as a param
    # @category = Category.find(Integer(category_id))
    # @income = @category.incomes.new(income_params)
    @income = Category.find(Integer(category_id)).incomes.new(income_params)
    if !params.has_key?(:category_id)
      @categories = Category.all
    end

    respond_to do |format|
      if @income.save
        # # byebug
        if params.has_key?(:category_id)
          @category = Category.find(params[:category_id])
          @incomes = Category.find(params[:category_id]).incomes
          redirect_url = category_incomes_path(@category)
        else
          redirect_url = incomes_url
        end
        format.html { redirect_to redirect_url, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to incomes_url, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def income_params
      params.require(:income).permit(:amount, :name)
    end
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/incomes/_form.html.erb
<%= form_for([@category, @income]) do |f| %>
  <% if @income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
      <% @income.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Only display the form if the database isn't empty. -->
  <% if !@category.nil? || !@categories.empty? %>
  <div id="content_create_new">
    
      <div class="field">
        <%= f.label :amount, :class => "create_label" %><br>
        <%= f.text_field :amount, :class => "create_text_field" %>
      </div>
      
      <div class="field">
        <%= f.label :name, :class => "create_label" %><br>
        <%= f.text_field :name, :class => "create_text_field" %>
      </div>
      
      <%if !@categories.nil? && !@categories.empty? %>
      <div class="field">
            <%= f.label :category_id, :class => "create_label" %><br>
            <%= f.collection_select :category_id, @categories, :id, :name, :include_blank => false %> 
      </div>
      <% end %>

      <div class="actions">
        <%= f.submit :class => "create_btn_submit" %>
      </div>

    </div>
  <% end %>

<% end %>

app/views/incomes/edit.html.erb
<div class="content_title_create">
      <p>Edit Income</p>
</div>

<%= render 'form' %>

<!-- <%= link_to 'Show', @income %> | -->
<!-- <%= link_to 'Back', incomes_path %> -->
<div class="back_nav">
    <%= link_to 'Cancel', incomes_path, :class => "btn_back" %>
</div>

app/views/incomes/index.html.erb
<p id="notice"><%= notice %></p>

<div class="content">
    <div class="content_title">
      <p>Listing Incomes</p>
    </div>


    <div class="create_new">
    <%= image_tag("btn_create") %>
    <% if !params.has_key?(:category_id) %>
      <%= link_to 'New Income', new_income_path %>
    <% else %>
      <%= link_to 'New Income', new_category_income_path(params[:category_id]) %>  
    <% end %>
  </div>


    <div id="content_transactions">
    <% @incomes.reverse.each do |income| %>
        
        <div class="transaction">

            <div class="transacts_transactions"> 
              <p class="transacts_transaction_name"><%= income.name %></p>
              <p class="transacts_transaction_amt">$<%= income.amount %></p>
            <!-- category.find(params[:category_id]).transactions --> 
            </div>

            <div class="category_options">
              <div class="cat_options">
                <!-- <%= image_tag("btn_edit") %> -->
                <p><%= link_to link_to image_tag("btn_edit.png"), edit_income_path(income) %></p>
                <!-- <%= image_tag("btn_delete") %> -->
                <p><%= link_to link_to image_tag("btn_delete.png"), income, method: :delete, data: { confirm: 'Are you sure?' } %></p>
              </div><!-- end cat_options -->
            </div><!-- end transaction_options -->

        </div><!-- end transaction -->
    <% end %>
    </div><!-- end content_transactions -->

    <br>

  <div class="back_nav">
    <%= link_to 'Back to categories.', categories_path, :class => "btn_back" %>
  </div>

</div><!-- end content -->

app/views/incomes/new.html.erb
<div class="content_title_create">
      <p>New Income</p>
</div>

<%= render 'form' %>

<div class="back_nav">
    <%= link_to 'Cancel', incomes_path, :class => "btn_back" %>
</div>

app/views/incomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @income.amount %>
</p>

<p>
  <strong>Name:</strong>
  <%= @income.name %>
</p>

<%= link_to 'Edit', edit_income_path(@income) %> |
<%= link_to 'Back', incomes_path %>