config/routes.rb
Rails.application.routes.draw do

  root :to => 'categories#index'

  resources :categories do 
    resources :transactions
    resources :incomes
  end
  
  resources :transactions
  resources :incomes
  

end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :transactions, dependent: :destroy
    has_many :incomes, dependent: :destroy
    # category should have a name and description to be added to the db
    validates :name, presence: true
    validates :description, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="content_create_new">
    <div class="field">
      <%= f.label :name, :class => "create_label" %><br>
      <%= f.text_field :name, :class => "create_text_field" %>
    </div>

    <div class="field">
      <%= f.label :description, :class => "create_label" %><br>
      <%= f.text_area :description, :class => "create_text_area" %>
    </div>

    <div class="actions">
      <%= f.submit :class => "create_btn_submit"%>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="content_title_create">
      <p>Edit Category</p>
</div>

<%= render 'form' %>

<!-- <%= link_to 'Show', @category %> | -->
<!-- <%= link_to 'Back', categories_path %> -->
<div class="back_nav">
    <%= link_to 'Cancel', categories_path, :class => "btn_back" %>
</div>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<div class="content">
  <!-- <h1>Listing Categories</h1> -->
  <div class="content_title">
    <p>Listing Categories</p>
  </div>

  <div class="create_new">
    <!-- <img src="wallet/app/assets/btn_create.png"> -->
    <%= link_to link_to image_tag("btn_create.png"), new_category_path, :class => "btn_create" %>
    <%= link_to "   New Category", new_category_path, :class => "btn_create" %>
    <!-- <%= image_tag("btn_create.png") %> -->
    <!-- <%= link_to 'New Category', new_category_path, :class => "btn_create"%> -->
  </div>

  <div id="content_categories">
      <% @categories.reverse.each do |category| %>

        <div class="category">
            <div class="category_name">
              <!-- <p><%= link_to category.name, category_transactions_path(category) %></p> -->
              <p><%= category.name %></p>
            </div><!-- end category_name -->

            <div class="cat_descriptions"> 
              <p><%= category.description %></p>
              <a class="content_cat_link">&#9643 &nbsp &nbsp<%= link_to "Incomes", category_incomes_path(category), :class => "content_cat_link" %></a>
              <br/>
              <a class="content_cat_link">&#9643 &nbsp &nbsp<%= link_to "Transactions", category_transactions_path(category), :class => "content_cat_link" %></a>
            <!-- category.find(params[:category_id]).transactions --> 
            </div>

            <div class="category_options">
              <div class="cat_options">
                <p><%= link_to link_to image_tag("btn_edit.png"), edit_category_path(category) %></p>
                <p><%= link_to link_to image_tag("btn_delete.png"), category, method: :delete, data: { confirm: 'Are you sure?' } %></p>
              </div><!-- end cat_options -->
            </div><!-- end category_options -->

        </div><!-- end category -->
      <% end %>

  </div><!-- end content_categories -->

  <!-- <div id="btn_new_category"> -->
    <!-- <%= button_to 'New Category', new_category_path, :class => "btn_create", :method => :get %> -->
  <!-- </div> -->

  <div class="back_nav">
    <p>&#9643 &nbsp &nbsp<%= link_to 'View All Incomes.', incomes_path, :class => "btn_back" %></p>
    <p>&#9643 &nbsp &nbsp<%= link_to 'View All Transactions.', transactions_path, :class => "btn_back" %></p>
  </div>

</div><!-- end content -->

app/views/categories/new.html.erb
<div class="content_title_create">
      <p>New Category</p>
</div>

<%= render 'form' %>

<div class="back_nav">
    <%= link_to 'Cancel', categories_path, :class => "btn_back" %>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>