config/routes.rb
Rails.application.routes.draw do

  root :to => 'categories#index'

  resources :categories do 
    resources :transactions
    resources :incomes
  end
  
  resources :transactions
  resources :incomes
  

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
    # @categories = Category.all

    if params.has_key?(:category_id)
      @category = Category.find(params[:category_id])
      @transactions = Category.find(params[:category_id]).transactions
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    # byebug
    if params.has_key?(:category_id)
      @category = Category.find(params[:category_id])
      @transaction = @category.transactions.new
    else
      @categories = Category.all
    end
  end

  # GET /transactions/1/edit
  def edit
    @categories = Category.all
  end

  # POST /transactions
  # POST /transactions.json
  def create
    puts "in create"
    # byebug
    category_id = (params[:category_id] or params[:transaction][:category_id])
    # Retrieve the id of the category that's passed in as a param
    @transaction = Category.find(Integer(category_id)).transactions.new(transaction_params)
    if !params.has_key?(:category_id)
      @categories = Category.all
    end

    
    # @transaction = Transaction.new(transaction_params)

    # @transaction = @category.transactions.create(transaction_params)
    

    respond_to do |format|
      if @transaction.save
        if params.has_key?(:category_id)
          @category = Category.find(params[:category_id])
          @transactions = Category.find(params[:category_id]).transactions
          redirect_url = category_transactions_path(@category)
        else
          redirect_url = transactions_url
        end
        format.html { redirect_to redirect_url, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transactions_url, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json 

  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:amount, :name, :category_id)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for([@category, @transaction]) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Only display the form if the database isn't empty. -->
  <% if !@category.nil? || !@categories.empty? %>

    <div id="content_create_new">
      <div class="field">
        <%= f.label :amount, :class => "create_label" %><br>
        <%= f.text_field :amount, :class => "create_text_field" %>
      </div>
      <div class="field">
        <%= f.label :name, :class => "create_label" %><br>
        <%= f.text_field :name, :class => "create_text_field" %>
      </div>

      <%if !@categories.nil? %>
      <div class="field">
            <%= f.label :category_id, :class => "create_label" %><br>
            <%= f.collection_select :category_id, @categories, :id, :name, :include_blank => false %> 
      </div>
      <% end %>
      
      <div class="actions">
        <%= f.submit :class => "create_btn_submit" %>
      </div>
    </div>

  <% end %>

<% end %>

app/views/transactions/_form_select_category.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="content_create_new">
    <div class="field">
      <%= f.label :amount, :class => "create_label" %><br>
      <%= f.text_field :amount, :class => "create_text_field" %>
    </div>
    <div class="field">
      <%= f.label :name, :class => "create_label" %><br>
      <%= f.text_field :name, :class => "create_text_field" %>
    </div>

    <div class="field">

      <%= f.label :category_id %><br>
      <!-- <%= f.text_field :category_id %> -->

      <%= f.collection_select :category_id, @cats, :id, :name %>
      
    </div>
    
    <div class="actions">
      <%= f.submit %>
    </div>
  
  </div>
<% end %>

app/views/transactions/edit.html.erb
<div class="content_title_create">
      <p>Edit Transaction</p>
</div>

<%= render 'form' %>

<!-- <%= link_to 'Show', @transaction %> | -->
<!-- <%= link_to 'Back', transactions_path %> -->
<div class="back_nav">
    <%= link_to 'Cancel', transactions_path, :class => "btn_back" %>
</div>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<div class="content">
  <!-- <h1>Listing Transactions</h1> -->
  <div class="content_title">
      <p>Listing Transactions</p>
  </div>

  <% if !@category.nil? %>
    <div id="transaction_cat_title">
      <div id="transaction_cat_title_top">
        <p class="heading1"><%= @category.name %></p>
      </div>
      <div id="transaction_cat_title_btm">
        <p class="heading2"><%= @category.description %></p>
      </div>
    </div>
  <% end %>

  <div class="create_new">
    <%= image_tag("btn_create") %>
    <% if !params.has_key?(:category_id) %>
      <%= link_to 'New Transaction', new_transaction_path %>
    <% else %>
      <%= link_to 'New Transaction', new_category_transaction_path(params[:category_id]) %>  
    <% end %>
  </div>

  <div id="content_transactions">
    <% @transactions.reverse.each do |transaction| %>

    <div class="transaction">

        <div class="transacts_transactions"> 
          <p class="transacts_transaction_name"><%= transaction.name %></p>
          <p class="transacts_transaction_amt">$<%= transaction.amount %></p>
        <!-- category.find(params[:category_id]).transactions --> 
        </div>

        <div class="category_options">
          <div class="cat_options">
            <!-- <%= image_tag("btn_edit") %> -->
            <p><%= link_to image_tag("btn_edit.png"), edit_transaction_path(transaction) %></p>
            <!-- <%= image_tag("btn_delete") %> -->
            <p><%= link_to image_tag("btn_delete.png"), transaction, method: :delete, data: { confirm: 'Are you sure?' } %></p>
          </div><!-- end cat_options -->
        </div><!-- end transaction_options -->

    </div><!-- end transaction -->
    <% end %>
  </div><!-- end content_transactions -->

  <br>

  <div class="back_nav">
    <%= link_to 'Back to categories.', categories_path, :class => "btn_back" %>
  </div>

</div><!-- end content -->

app/views/transactions/new.html.erb
<div class="content_title_create">
      <p>New Transaction</p>
</div>

<!-- <div id="create_pg_content"> -->

    <%= render 'form' %>


<div class="back_nav">
    <%= link_to 'Cancel', categories_path, :class => "btn_back" %>
</div>
<!-- </div> -->

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Name:</strong>
  <%= @transaction.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @transaction.category.name %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>